site_name: EMS-ESP
site_description: Documentation (Wiki) for EMS-ESP
site_url: https://emsesp.github.io/docs/
repo_name: 'emsesp/EMS-ESP32'
repo_url: 'https://github.com/emsesp/EMS-ESP32'
edit_uri: 'https://github.com/emsesp/docs/blob/master/docs/'
docs_dir: docs
# copyright: 'Copyright &copy; 2022 Proddy and MichaelDvP'

plugins:
  - search
  - alternate-link
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
  - table-reader
  - git-revision-date-localized
  # - git-committers:
  #     repository: emsesp/docs
  #     branch: main
# - htmlproofer

# strict: true

theme:
  name: material
  language: 'en'
  # custom_dir: 'overrides'
  logo: '_media/logo/boiler.svg'
  favicon: _media/favicon.ico
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

  font:
    text: Barlow
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/discord
      link: 'https://discord.gg/3J3GgnzpyT'
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/emsesp/EMS-ESP32'
  analytics:
    provider: google
    property: G-SVDSJ3QTVC
  generator: false

markdown_extensions:
  - admonition
  - toc:
      permalink: '~'
      toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tilde
  - meta
  - def_list
  - attr_list
  - md_in_html

extra_css:
  - 'assets/css/anchor-fix.css'
  - 'assets/css/github.css'

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - extra_javascript/tablesort.js
  - extra_javascript/github.js

nav:
  - Home:
      - News: index.md
      - About EMS-ESP: About.md
      - Version Release History: Version-Release-History.md
      - Getting Started: Getting-Started.md
      - Configuring: Configuring.md
      - Special Functions: Special-Functions.md
      - WebUI: WebUI.md
      - MQTT: MQTT.md
      - Modbus/TCP:
          - Modbus: Modbus.md
          - Settings: Modbus-Settings.md
          - Server Unit Identifiers: Modbus-Server-IDs.md
          - The SYSTEM Server: Modbus-System-Server.md
          - Register Block Offsets: Modbus-Register-Blocks.md
          - Entity Register Offsets: Modbus-Entity-Registers.md
      - Commands: Commands.md
      - Console: Console.md
      - For Developers:
          - Building & Testing the Firmware: Building.md
          - Adding Languages: Adding-Languages.md
          - Contributing: Contributing.md
          - The EMS protocol: EMS-bus.md
          - Maintaining Modbus Parameters: Modbus-Dev.md
  - Supported Devices:
      - All Devices and Entities: All-Devices.md
      - Boilers: Boilers.md
      - Thermostats: Thermostats.md
      - Solar Modules: Solar-Modules.md
      - Mixer Modules: Mixer-Modules.md
      - Heat Pumps: Heat-Pumps.md
      - Controllers: Controllers.md
      - Switches: Switches.md
      - Other Devices: Other-Devices.md
  - Integrations:
      - Introduction: Integrations.md
      - Home Assistant: Home-Assistant.md
      - IOBroker: IOBroker.md
      - Domoticz: Domoticz.md
      - openHAB: openHAB.md
      - Loxone: Loxone.md
      - Grafana: Grafana.md
      - Modbus: Modbus.md
  - Help:
      - Support: Support.md
      - Troubleshooting: Troubleshooting.md
      - FAQ: FAQ.md
      - Tips & Tricks: tips-and-tricks.md
